# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.sameSRS <- function(x, y) {
    .Call(`_terra_sameSRS`, x, y)
}

.getSRSname <- function(s) {
    .Call(`_terra_getCRSname`, s)
}

.getLinearUnits <- function(s) {
    .Call(`_terra_getLinearUnits`, s)
}

.geotransform <- function(fname) {
    .Call(`_terra_geotransform`, fname)
}

.gdalinfo <- function(filename, options, oo) {
    .Call(`_terra_ginfo`, filename, options, oo)
}

.sdinfo <- function(filename) {
    .Call(`_terra_sd_info`, filename)
}

.gdalversion <- function() {
    .Call(`_terra_gdal_version`)
}

.metadata <- function(filename) {
    .Call(`_terra_metatdata`, filename)
}

.sdsmetadata <- function(filename) {
    .Call(`_terra_sdsmetatdata`, filename)
}

.parsedsdsmetadata <- function(filename) {
    .Call(`_terra_sdsmetatdataparsed`, filename)
}

.gdaldrivers <- function() {
    .Call(`_terra_gdal_drivers`)
}

.set_gdal_warnings <- function(level) {
    invisible(.Call(`_terra_set_gdal_warnings`, level))
}

.gdalinit <- function(path) {
    invisible(.Call(`_terra_gdal_init`, path))
}

