# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.gdalinfo <- function(filename, options, oo) {
    .Call(`_terra_ginfo`, filename, options, oo)
}

.sdinfo <- function(filename) {
    .Call(`_terra_sd_info`, filename)
}

.gdalversion <- function() {
    .Call(`_terra_gdal_version`)
}

.gdalinit <- function(path) {
    invisible(.Call(`_terra_gdal_init`, path))
}

