on:
  workflow_dispatch:
    inputs:
      which:
        type: choice
        description: Which dependents to check
        options:
        - strong
        - most
        - Depends
        - Imports
        - Suggests
      pattern:
        type: string
        description: 'case insensitive pattern to subset packages'
        default: 'a-z'
        
name: Reverse dependency check

jobs:
  revdep_check:
    name: Reverse check ${{ inputs.which }} dependents
    #uses: r-devel/recheck/.github/workflows/recheck.yml@v1
    uses: ./.github/workflows/recheck_pattern.yaml
    with:
      which: ${{ inputs.which }}
      pattern:  ${{ inputs.pattern }}

